config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :budgets

  root 'welcome#index'

  get 'contacto'=>'welcome#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  validates :name, :address, presence: true
  validates :phone, presence: true
  validates :phone, length: { is: 9 }
  validates :phone, numericality: { only_integer: true }
  validates :observations, length: { minimum: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:new, :show, :create]

  

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        UserMailer.welcome_email(@budget).deliver_now
        format.html { redirect_to @budget, notice: 'Su presupuesto ha sido correctamente creado' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Su presupuesto ha sido actualizado' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Presupuesto destruido' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:name, :address, :email, :phone, :observations, :workday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/budgets/_form.html.erb
<%= form_with(model: budget, local: true) do |form| %>
  <% if budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget.errors.count, "error impide", "errores impiden") %> que este presupuesto sea enviado:</h2>

      <ul>
      <% budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :nombre, class: "col-sm-5 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :name, id: :budget_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :dirección, class: "col-sm-5 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :address, id: :budget_address, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :email, class: "col-sm-5 col-form-label" %>
    <div class="col-sm-10">
      <%= form.email_field :email, id: :budget_email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :Teléfono, class: "col-sm-5 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :phone, id: :budget_phone, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :Observaciones, class: "col-sm-5 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_area :observations, id: :budget_observations, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :Día_de_trabajo, class: "col-sm-5 col-form-label" %>
    <div class="col-sm-10">
      <%= form.datetime_local_field :workday, id: :budget_workday, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%=form.submit(options={class: "btn btn-primary"}) %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Budgets</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Observations</th>
      <th>Workday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <td><%= budget.name %></td>
        <td><%= budget.address %></td>
        <td><%= budget.email %></td>
        <td><%= budget.phone %></td>
        <td><%= budget.observations %></td>
        <td><%= budget.workday %></td>
        <td><%= link_to 'Show', budget %></td>
        <td><%= link_to 'Edit', edit_budget_path(budget) %></td>
        <td><%= link_to 'Destroy', budget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget', new_budget_path %>

app/views/budgets/new.html.erb
<h1>Nuevo presupuesto</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Volver a inicio', root_path %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @budget.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @budget.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @budget.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @budget.phone %>
</p>

<p>
  <strong>Observations:</strong>
  <%= @budget.observations %>
</p>

<p>
  <strong>Workday:</strong>
  <%= @budget.workday %>
</p>

<%= link_to 'Inicio', root_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CleanTech</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Indie+Flower">
    <style>
      body {
        font-family: 'Indie Flower', serif;
        font-size: 25px;
      }
    </style>
    <%= favicon_link_tag '/images/favicon.ico' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <%= link_to "Inicio", root_path, class:"btn btn-success" %>
      <%= link_to "Presupuesto", new_budget_path, class: "btn btn-success" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
      </button>
      
          <% if user_signed_in? %>
              <%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-success" %>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-success" %>
            <% else %>
              <%= link_to "Acceder", new_user_session_path, class: "btn btn-success" %>
          <% end %>

    </nav>
    <div class="progress">
      <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/contact.html.erb
<br />
<p class="text-center">
   Made with &#9829; for <a target="_blank" href="https://github.com/Cafergut">Carlos</a>
  &
  <a target="_blank" href="https://github.com/wimel">Wimel</a> 	&#174;
</p>
<div class="text-center">
  <img src="https://media.giphy.com/media/26gscNQHswYio5RBu/giphy.gif" alt="Limpiador" style="width:480px;height:480px;">
</div>
<p class="text-center">
  Donations ar<span class="basic-font">Ξ</span> w<span class="basic-font">Ξ</span>lcom<span class="basic-font">Ξ</span>:
  <p class="text-center">
    0x3BE41c8FC6307f07e4E03928cD44405A032589FE
  </p>
</p>
<div class="text-center">
  <img src="/images/ETH.jpg"/>
</div>
<%= link_to "Contacto", contacto_path, class: "btn btn-success btn-block" %>

app/views/welcome/index.html.erb
<h1 class="text-center">CleanTech</h1>
<p class="text-center">Ensucia, nosotros limpiamos</p>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
<ol class="carousel-indicators">
  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
</ol>
<div class="carousel-inner">
  <div class="carousel-item active">
    <img class="d-block w-100" src="http://limpiezasmaiz.es/wp-content/uploads/2015/06/limpieza.jpg" alt="First slide">
  </div>
  <div class="carousel-item">
    <img class="d-block w-100" src="http://herafs.com/wp-content/uploads/2016/04/empresas-de-limpieza-en-madrid-suelos.jpg" alt="Second slide">
  </div>
  <div class="carousel-item">
    <img class="d-block w-100" src="http://78.media.tumblr.com/7e7323e1efc1480847f884b29f09bf17/tumblr_n8reguhMO71tpaqwwo1_1280.jpg" alt="Third slide">
  </div>
</div>
<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  <span class="sr-only">Anterior</span>
</a>
<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
  <span class="carousel-control-next-icon" aria-hidden="true"></span>
  <span class="sr-only">Siguiente</span>
</a>
</div>
<div>
  <p>
    <h1>
      Empresa Andaluza dedicada a la limpieza, dejamos las cosas como a usted le
      gustaría dejarlas, tenemos personal junior que se adapta a sus necesidades.
    </h1>
  </p>
  <p>
    Pida <a><%= link_to "presupuesto", new_budget_path %></a> sin compromiso, atendemos en toda Andalucía.
  </p>
</div>

  <%= link_to "Contacto", contacto_path, class: "btn btn-success btn-block" %>